fix PythonPackage installation with $PIP_REQUIRE_VIRTUALENV
The user using EasyBuild might have $PIP_REQUIRE_VIRTUALENV set which
will fail the installation of PythonPackages with
> ERROR: Could not find an activated virtualenv (required).

So disable this. pip 20.2.3+ seems to require `false` as the value
instead of any other value (including the empty string)